# Generated by Django 6.0.6 on 2026-08-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='kind',
            field=models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=16),
        ),
    ]
