# Generated by Django 6.0.6 on 2026-08-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
