# Generated by Django 6.0.6 on 2026-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessmodel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='area',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
