# Generated by Django 6.0.6 on 2026-08-12 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ticket_prefix', models.CharField(max_length=2)),
                ('avg_duration_sec', models.PositiveIntegerField(default=600)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.businessmodel')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'queue_service',
            },
        ),
        migrations.CreateModel(
            name='QueueEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField()),
                ('ticket_code', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'In progress'), ('served', 'Served'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], default='waiting', max_length=16)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('ticket_date', models.CharField(db_index=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='businesses.businessmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='queue.servicemodel')),
            ],
            options={
                'verbose_name': 'queue entry',
                'verbose_name_plural': 'queue entries',
                'db_table': 'queue_queueentry',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicemodel',
            index=models.Index(fields=['business', 'is_active', 'display_order'], name='queue_servi_busines_e4a945_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicemodel',
            constraint=models.UniqueConstraint(fields=('business', 'ticket_prefix'), name='uniq_business_prefix'),
        ),
        migrations.AddIndex(
            model_name='queueentrymodel',
            index=models.Index(fields=['service', 'status', 'ticket_number'], name='queue_queue_service_b7dc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentrymodel',
            index=models.Index(fields=['business', 'created_at'], name='queue_queue_busines_59bf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentrymodel',
            index=models.Index(fields=['user', 'status'], name='queue_queue_user_id_6173c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='queueentrymodel',
            constraint=models.UniqueConstraint(fields=('service', 'ticket_number', 'ticket_date'), name='uniq_ticket_per_day'),
        ),
    ]
