# Generated by Django 6.0.6 on 2026-08-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_admin'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='businesses.businessmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('staff', 'staff'), ('admin', 'admin')], default='customer', max_length=16),
        ),
    ]
